---
# tasks file for zabbix-agent
- name: dependencies
  apt:
    name: apt-transport-https
    state: present
    update_cache: yes

- name: wget
  shell: wget -O /tmp/zabbix.deb https://repo.zabbix.com/zabbix/7.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_latest_7.0+ubuntu24.04_all.deb

- name: dpkg
  shell: dpkg -i /tmp/zabbix.deb

- name: apt update
  apt:
    update_cache: yes

- name: install zabbix-agent
  apt:
    name: zabbix-agent
    state: present

- name: copy zabbix_agentd.conf
  template:
    src: zabbix_agentd.conf
    dest: /etc/zabbix/zabbix_agentd.conf
  notify:
    - restart zabbix-agent

- name: specify hostname
  lineinfile:
    path: /etc/zabbix/zabbix_agentd.conf
    regexp: '^Hostname='
    line: "Hostname={{inventory_hostname}}"
    backup: yes

#- name: copy zabbix_agentd.conf.d
#  template:
#    src: zabbix_agentd.conf
#    dest: /etc/zabbix/zabbix_agentd.d/zabbix_agentd.conf
#  notify:
#    - restart zabbix-agent

#- name: specify hostname
#  lineinfile:
#    path: /etc/zabbix/zabbix_agentd.d/zabbix_agentd.conf
#    regexp: '^Hostname='
#    line: "Hostname={{inventory_hostname}}"
#    backup: yes

