---
# vars file for docker

docker_gpg_url: https://download.docker.com/linux/ubuntu/gpg
docker_repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
docker_compose_url: https://github.com/docker/compose/releases/latest/download/docker-compose-{{ ansible_system | lower }}-{{ ansible_machine }}

